apiVersion: v1
kind: Service
metadata:
  name: diseasecontrol-service
  app: app
spec:
  type: LoadBalancer
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    name: diseasecontrol-pod
    app: app
